### ISSUE TITLE
Does panel support bokeh > 3.0?

### ISSUE THREAD

**Issue by heather999** [conda-forge/panel-feedstock#55]
### Comment:

I'm interested in installing panel and bokeh in the same conda environment.  Bokeh's lastest release is 3.0.3, but panel's conda-forge recipe seems to exclude bokeh > 2.5?  Bokeh 3.0.0 came out in Oct 2022 - is it possible that panel can work with the more recent versions of bokeh?  Can this recipe be updated?

https://github.com/conda-forge/panel-feedstock/blob/65cf55bac26c0db2a47211801939eafa6bff03c4/recipe/meta.yaml#L26

**Comment by philippjfr** [comment]
Currently we do not support Bokeh 3.0. Bokeh 3.0 constitutes a major redesign of a lot of the styling and layout internals and we are hard at work to update Panel to support these changes. We will have a dev release with Bokeh 3.0 support some time next week and plan to release Panel 1.0 with full support in February.

**Comment by maximlt** [comment]
Panel 1.0 has been released with Bokeh 3 support.
